# Generated by Django 4.0.6 on 2022-08-13 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_question_istext_questionvalue_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyquestion',
            name='question',
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='isText',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.questionvalue'),
        ),
    ]
