# Generated by Django 4.0.6 on 2022-08-13 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_surveyquestion_question_surveyquestion_istext_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyquestion',
            name='value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.question'),
        ),
    ]
