# Generated by Django 4.0.6 on 2022-08-13 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_surveyquestion_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='responden',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.questionvalue'),
        ),
    ]
