# Generated by Django 4.0.6 on 2022-08-13 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_responden_value_alter_responden_survey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responden',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='responden',
            name='date',
        ),
        migrations.RemoveField(
            model_name='responden',
            name='value',
        ),
        migrations.CreateModel(
            name='ResponSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.questionvalue')),
                ('respond', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.responden')),
                ('value', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.surveyquestion')),
            ],
        ),
    ]
