# Generated by Django 4.0.6 on 2022-08-13 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_responden_answer_remove_responden_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyquestion',
            name='text',
        ),
        migrations.AddField(
            model_name='responsurvey',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
