# Generated by Django 4.0.6 on 2022-08-14 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_surveyquestion_text_responsurvey_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='master',
            field=models.BooleanField(default=False),
        ),
    ]
