# Generated by Django 4.0.6 on 2022-08-14 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_user_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsvValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=225)),
                ('freq', models.IntegerField(default=1)),
                ('csv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.question')),
            ],
        ),
    ]
