# Generated by Django 4.0.6 on 2022-08-14 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_csvvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvvalue',
            name='csv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.csv'),
        ),
    ]
