# Generated by Django 4.0.6 on 2022-08-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_csvvalue_csv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layanan', models.CharField(max_length=225)),
                ('setuju', models.IntegerField()),
                ('sangat_setuju', models.IntegerField()),
                ('tidak_setuju', models.IntegerField()),
                ('sangat_tidak_setuju', models.IntegerField()),
            ],
        ),
    ]
