# Generated by Django 4.0.6 on 2022-08-18 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_layanan'),
    ]

    operations = [
        migrations.AddField(
            model_name='layanan',
            name='csv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.csv'),
        ),
        migrations.AlterField(
            model_name='layanan',
            name='sangat_setuju',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='layanan',
            name='sangat_tidak_setuju',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='layanan',
            name='setuju',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='layanan',
            name='tidak_setuju',
            field=models.IntegerField(default=0),
        ),
    ]
