# Generated by Django 3.2.7 on 2022-08-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_layanan_csv_alter_layanan_sangat_setuju_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvvalue',
            name='value',
            field=models.TextField(),
        ),
    ]
